### ISSUE TITLE
The type or namespace name 'FaLinksPropertyEditor' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by itsbhawnajain** [mjbarlow/Font-Awesome-Links-Property-Editor#2]
I am using strongly typed version, and this is the error which I am getting when trying to compile my project:
The type or namespace name 'FaLinksPropertyEditor' could not be found (are you missing a using directive or an assembly reference?)
![image](https://user-images.githubusercontent.com/30106472/58684560-48ba1b00-8396-11e9-92d5-45dbeb4917c2.png)

**Comment by mjbarlow** [comment]
Ok, sounds like it's missing the Fonts Package - could try and install via nuget. 
Install-Package FontAwesomePropertyEditor 

https://www.nuget.org/packages/FontAwesomePropertyEditor/
